name: Perforce Helix Core Actions
author: Perforce Software
description: Run p4 commands within your GitHub Actions Workflows
inputs:
  command:
    description: p4 command to execute
    required: true
  global_options:
    description: arguments for p4 cli that go before p4 command
    required: false
  arguments:
    description: arguments for p4 cli that go after p4 command
    required: false
  spec:
    description: This is the P4 spec contents for the resource you are creating
    required: false
  p4_version:
    description: >-
      Version of P4 binary to use.  When a step has this set it will download
      and install the P4 CLI.
    required: false
    default: 21.2
  working_directory:
    description: The working directory to use when running p4 commands.
    required: false
    default: .
outputs:
  stdout:
    description: Standard output from the p4 command
  stderr:
    description: Standard error from the p4 command
  exit_code:
    description: Exit code from p4 command
runs:
  using: node16
  main: dist/index.js
branding:
  color: blue
  icon: package
