on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron:  '30 1 * * *'

name: CI Integration

jobs:

  integration:
    name: integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-10.15, macos-11, windows-2022, windows-2019]

    env:
      P4PORT: ${{ secrets.P4PORT }}
      P4USER: ${{ secrets.P4USER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: p4 login
        uses: ./
        id: login
        with:
          command: login
        env:
          P4PASSWD: ${{ secrets.P4PASSWD }}

      - name: p4 client
        uses: ./
        id: client
        with:
          command: client
          arguments: -i

          spec: |
            Client:	github-actions-setup-p4
            Owner: ${{ secrets.P4USER }}
            Description:
              Created by ${{ secrets.P4USER }}.
            Root:	/tmp
            Options:	noallwrite noclobber nocompress unlocked modtime rmdir
            SubmitOptions:	leaveunchanged
            LineEnd:	local
            View:
              //guest/perforce_software/sdp/... //github-actions-setup-p4/guest/perforce_software/sdp/...

      - name: p4 sync
        uses: ./
        id: sync
        env:
          P4CLIENT: github-actions-setup-p4
        with:
          command: sync
          arguments: -f
