on:
  workflow_dispatch:
  push:
  pull_request:

name: CI

jobs:

  unit:
    name: unit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  smoke:
    name: smoke
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12, windows-2022, windows-2019]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: p4 info 21.1
        uses: ./
        with:
          p4_version: 21.1
          command: -V

      - name: p4 info 21.2
        uses: ./
        with:
          p4_version: 21.2
          command: -V

      - name: p4 info 21.2
        uses: ./
        with:
          p4_version: 21.2
          command: -V
